ログイン作成
atsuya02/promote-music-app pull request #10
Opened 2021-09-21 16:20 UTC by atsuya02

2021-09-21 18:11 UTC, atsuya02 commented
https://user-images.githubusercontent.com/73219274/134224782-44a69941-3b6b-49d7-bd92-7fd1371285a4.mov

2021-09-22 13:08 UTC, YuyaYoshioka commented on client/src/App.tsx
> +import LoginPage from 'pages/login';
ディレクトリ名とコンポーネント名を揃えてもよさそう

2021-09-22 13:09 UTC, atsuya02 commented
https://user-images.githubusercontent.com/73219274/134349439-8a221173-d51d-4568-93bc-b7ebad248758.mov

2021-09-22 13:21 UTC, YuyaYoshioka commented on client/src/pages/login.tsx
> +  });
依存配列なくて，無限ループしてる

2021-09-22 13:24 UTC, YuyaYoshioka commented on client/src/lib/login.ts
> +};
Userを全て取得して，そのnameが等しいかどうかで判断するのではなく，nameもしくは，idでrails 側で`find_by`すればよいのでは？

2021-09-22 13:26 UTC, YuyaYoshioka commented on client/src/components/Header.tsx
> +  const [user, setUser] = useState<User | undefined>();
`const [user, setUser] = useState<User>({
  id: 0,
  name: '',
});`
で初期化しておけばよさそう。

2021-09-22 13:27 UTC, YuyaYoshioka commented on client/src/components/Header.tsx
> +    setUser(JSON.parse(localStorage.getItem('loginUser') || '[]'));
localstorageには，Userのnameだけを保存すればよいのでは？
` || '[]'`じゃなくで，`|| ""`でよさそう

2021-09-22 14:08 UTC, YuyaYoshioka commented on client/src/pages/login.tsx
> +    const user = JSON.parse(localStorage.getItem('loginUser') || '[]') as User;
同様にメソッドに切り出したい

2021-09-22 14:10 UTC, YuyaYoshioka commented on client/src/pages/login.tsx
> +      navigate('/');
上の方で指摘したように，valueを引数としてrailsのAPIを叩きたい
あと，localStorageに保存するのは，nameだけでいいのでは？

2021-09-22 14:16 UTC, YuyaYoshioka commented on client/src/pages/signup.tsx
> +  });
loginでも，signupでも使っているから，この処理は`App.tsx`に移したい
https://github.com/YuyaYoshioka/bookshelf-app/blob/main/client/src/App.tsx#L37-L39
こんな感じでいけそう？

2021-09-22 14:16 UTC, YuyaYoshioka requested changes
レビューした

2021-09-22 14:19 UTC, YuyaYoshioka commented on server/app/graphql/types/query_type.rb
> +    end
別にこれはログインに限る必要はないから，`login_user`でなくていいのでは？

2021-09-22 17:40 UTC, YuyaYoshioka commented on client/src/lib/localStorageGetItem.ts
> +};
```
const localStorageGetItem = (): string => {
  const userName = localStorage.getItem(LOCAL_STORAGE_KEY || "");

  return userName;
};
```
とかでよいのでは？

2021-09-22 17:42 UTC, YuyaYoshioka commented on client/src/components/Header.tsx
> +    setUserName(localStorageUserName || '');
ここの` || ''`も
https://github.com/atsuya02/promote-music-app/pull/10/files#r714170125
でいらなくなりそう

2021-09-23 08:11 UTC, atsuya02 commented
@YuyaYoshioka 
修正終わったよ

2021-09-23 09:05 UTC, YuyaYoshioka commented on client/src/constant.ts
> +export const LOCAL_STORAGE_KEY = 'loginUser';
localStorage の  key って複数ありえるだろうから， `LOCAL_STORAGE_LOGIN_USER_KEY`とか？

2021-09-23 09:24 UTC, YuyaYoshioka commented on client/src/pages/loginPage.tsx
> +        localStorage.setItem('loginUser', data.userByName.name);
`loginUser` じゃなくて定数名使いたい
あと，
```
localStorage.setItem('loginUser', data.userByName.name);
```
全体も別の関数に切り出したい。他のところでも使うやろうから

2021-09-23 09:26 UTC, YuyaYoshioka commented on client/src/pages/loginPage.tsx
> +  const handleClick = () => {
ここは，わかりやすいように，`handleLogin`とかでいいのでは？

2021-09-23 09:29 UTC, YuyaYoshioka commented on client/src/pages/signupPage.tsx
> +        );
同じく関数に切り出したい

2021-09-23 09:30 UTC, YuyaYoshioka reviewed
@atsuya02 
レビューした

2021-09-23 11:48 UTC, atsuya02 commented
@YuyaYoshioka 
修正終わったよ

2021-09-23 12:22 UTC, YuyaYoshioka approved these changes
LGTM

2021-09-23 12:22 UTC, merged