ログアウト機能
atsuya02/promote-music-app pull request #11
Opened 2021-09-22 13:50 UTC by atsuya02

2021-09-22 13:51 UTC, atsuya02 commented
https://user-images.githubusercontent.com/73219274/134356484-7fd7bc0d-67e1-4de5-8381-b1effa07184b.mov

2021-09-23 12:42 UTC, YuyaYoshioka commented on client/src/lib/logout.ts
> +const logout = (): void => {
logoutとsignoutどっちかに統一したい

2021-09-23 12:43 UTC, YuyaYoshioka commented on client/src/pages/signoutPage.tsx
> +export default SignoutPage;
ログアウト用のページがあるって変では？
ヘッダー上にログアウトのタグを追加した方が良さそう

2021-09-23 12:43 UTC, YuyaYoshioka requested changes
レビューした

2021-09-23 13:35 UTC, YuyaYoshioka approved these changes
👍

2021-09-23 13:35 UTC, merged