[フォロー中、フォローするボタン実装
atsuya02/promote-music-app pull request #21
Opened 2021-09-27 17:29 UTC by atsuya02

2021-09-28 07:37 UTC, atsuya02 commented
@YuyaYoshioka 
確認お願い

2021-09-28 11:16 UTC, atsuya02 commented
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/73219274/135076776-c5574d86-7063-4be7-a1f9-cabb4783e2b4.png">

2021-09-28 11:20 UTC, YuyaYoshioka commented
descriptionは実装と機能は分けて書いた方がいい

2021-09-28 12:39 UTC, YuyaYoshioka commented on client/src/components/UserArtistRelationship.tsx
> +const UserArtistRelationship: FC<UserArtistRelationshipProp> = ({
`FollowButton`とかでいいのでは？

2021-09-28 12:39 UTC, YuyaYoshioka commented on client/src/components/UserArtistRelationship.tsx
> +  loginUserName: string;
`currentUserName`とか？

2021-09-28 12:43 UTC, YuyaYoshioka commented on client/src/components/UserArtistRelationship.tsx
> +  const [loginUserArtists, setLoginUserArtists] = useState<Set<Artist>>();
`currentUserArtists`とかかな？

2021-09-28 12:44 UTC, YuyaYoshioka commented on client/src/components/UserArtistRelationship.tsx
> +          フォロー中
「フォロー解除」で良さそう

2021-09-28 12:44 UTC, YuyaYoshioka commented on client/src/components/UserArtistRelationship.tsx
> +          フォローする
「フォロー」で良さそう

2021-09-28 12:48 UTC, YuyaYoshioka commented on client/src/components/UserArtistRelationship.tsx
> +      },
ボタンの数だけAPI叩いているのはパフォーマンス上良くない😇

2021-09-28 12:49 UTC, YuyaYoshioka requested changes
フォローボタンに，ログインしている User がフォローしている Artist を props で渡してあげたらよいのでは

2021-09-28 12:54 UTC, atsuya02 commented on client/src/components/UserArtistRelationship.tsx
> +      },
ApolloClientのキャッシュ機構で大丈夫そう
心掛けとして修正します

2021-09-28 13:30 UTC, atsuya02 commented on client/src/components/UserArtistRelationship.tsx
> +          フォロー中
ホバー時に「フォロー解除」が出るようにする

2021-09-28 14:44 UTC, YuyaYoshioka commented on client/src/components/ArtistListElementCard.tsx
> +  }, []);
`setCurrentUserName`を依存配列に入れておこう

2021-09-28 14:55 UTC, YuyaYoshioka commented on client/src/components/ArtistListElementCard.tsx
> +  );
今欲しいのは，`currentUserArtists`だけだから，これをpropsで`ArtistListElement `に渡してあげよう

2021-09-28 14:55 UTC, YuyaYoshioka requested changes
propsのところを修正しよう

2021-09-28 14:56 UTC, YuyaYoshioka commented on client/src/components/ArtistListElementCard.tsx
> +                  </Button>
これも`FollowButton`で書けば良さそう

2021-09-29 13:56 UTC, YuyaYoshioka commented on client/src/components/ArtistListElementCard.tsx
> +import UserArtistRelationship from 'components/FollowButton';
`FollowButton`かな

2021-09-29 14:03 UTC, YuyaYoshioka commented on client/src/components/ArtistsCard.tsx
> +  const [currentUserArtists, setCurrentUserArtists] = useState<Set<Artist>>();
`useState<Set<Artist>>(new Set())`で初期化しておけばいいかな

2021-09-29 14:04 UTC, YuyaYoshioka commented on client/src/components/ArtistListElementCard.tsx
> +  currentUserArtists: Set<Artist> | undefined;
> useState<Set<Artist>>(new Set())で初期化しておけばいいかな

ここが `undefined` でなくなる

2021-09-29 14:04 UTC, YuyaYoshioka commented on client/src/components/FollowButton.tsx
> +  currentUserArtists: Set<Artist> | undefined;
> useState<Set<Artist>>(new Set())で初期化しておけばいいかな

ここも `undefined` でなくなる

2021-09-29 14:07 UTC, YuyaYoshioka commented on client/src/components/ArtistListElementCard.tsx
> +            )}
かっこいらなさそう
```
            {currentUserName &&
              <UserArtistRelationship
                artist={artist}
                currentUserArtists={currentUserArtists}
                loading={loading}
              />
            }
```

2021-09-29 15:08 UTC, YuyaYoshioka requested changes
`useLazyQuery`の`loading`がなぜか作用しないから，自分でstateで管理した方がいいかも
そしたら，` || !currentUserArtists`この分岐もいらなくなる
```
const ArtistsCard: FC<ArtistsCardProps> = ({ artists }) => {
  const [currentUserName, setCurrentUserName] = useState<string>('');
  const [currentUserArtists, setCurrentUserArtists] = useState<Set<Artist>>(new Set());
  const [loading, setLoading] = useState<boolean>(false);
  const [getUserByName] = useLazyQuery<
    { userByName: User },
    UserByNameInput
  >(getUserByNameQuery, {
    variables: { name: currentUserName },
    onCompleted: (res) => {
      setCurrentUserArtists(new Set(res.userByName.artists));
      setLoading(false);
    },
    onError: (e: ApolloError) => {
      toast.error(e.message);
    },
  });

  useEffect(() => {
    setCurrentUserName(getLoginUserName());
  }, [setCurrentUserName]);

  useEffect(() => {
    setLoading(true)
    if (currentUserName) {
      getUserByName();
    }
  }, [currentUserName, getUserByName]);
```

2021-09-30 11:07 UTC, atsuya02 commented on client/src/components/ArtistListElementCard.tsx
> +            )}
eslintの設定で勝手に()が増えてるかも

2021-09-30 11:09 UTC, atsuya02 commented
`useLazyQuery`の`loading`の問題は次のbranchで修正する

2021-09-30 12:43 UTC, YuyaYoshioka approved these changes
LGTM

2021-09-30 13:12 UTC, merged