GraphQLクエリのテスト
atsuya02/promote-music-app pull request #36
Opened 2021-11-05 08:51 UTC by atsuya02

2021-11-07 16:39 UTC, atsuya02 commented
@YuyaYoshioka 
確認お願い

2021-11-19 14:35 UTC, YuyaYoshioka commented on server/spec/queries/artists_spec.rb
> +      end
`let!("artist_#{n + 1}".to_s)` これだとシンボルじゃなくて，文字列になっている。
しかも，今回は`artist_1`とかを参照しないのだから，beforeとかで作れば良いのでは？
```suggestion
      before do
        create_list(:artist, 5) do |artist, i|
          artist.name = "artist#{i+1}"
        end
      end
```

https://github.com/thoughtbot/factory_bot/issues/787#issuecomment-619814046

2021-11-19 14:35 UTC, YuyaYoshioka commented on server/spec/queries/artists_spec.rb
> +        expect(result_data).to eq 5.times.map { |n| {"id" => "#{n + 1}", "name" => "artist#{n + 1}"}}
テスト対象のデータはベタ書きにすべき

2021-11-19 14:36 UTC, YuyaYoshioka commented on server/spec/queries/users_spec.rb
> +      end
同上

2021-11-19 14:39 UTC, YuyaYoshioka commented on server/spec/queries/current_user_artists_spec.rb
> +      end
同上

2021-11-19 14:39 UTC, YuyaYoshioka requested changes
レビューした

2021-11-19 14:53 UTC, YuyaYoshioka commented on server/spec/queries/current_user_artists_spec.rb
> +      let!(:user_artist_3) { create(:user_artist, user: user, artist: artist_3) }
ここはbeforeで良さそう

2021-11-19 14:55 UTC, YuyaYoshioka commented on server/spec/queries/current_user_artists_spec.rb
> +      let!(:user_artist_3) { create(:user_artist, user: user, artist: artist_3) }
そもそも，こんな感じでいい気がする。
```suggestion
      before do
        create_list(:artist, 3) do |artist, i|
          artist.name = "artist#{i+1}"
          artist.users = [user]
        end
        create_list(:artist, 3) do |artist, i|
          artist.name = "artist#{i+100}"
        end
      end
```

2021-11-20 15:44 UTC, atsuya02 commented
@YuyaYoshioka 
修正終わったよ

2021-11-20 16:14 UTC, YuyaYoshioka approved these changes
LGTM

2021-11-20 16:16 UTC, merged