ユーザー更新ページ作成
atsuya02/promote-music-app pull request #39
Opened 2021-11-11 09:18 UTC by atsuya02

2021-11-11 16:37 UTC, atsuya02 commented on client/src/pages/userPage.tsx
> +            {loginUser === paramsUserName && (
`loginUser === paramsUserName`を`getLoginUserName() === paramsUserName`で実装した方がいい？

2021-11-11 16:41 UTC, atsuya02 commented
@YuyaYoshioka 
確認お願い

2021-11-15 11:51 UTC, atsuya02 commented
https://user-images.githubusercontent.com/73219274/141777346-fd38fcbb-8078-4348-8fb4-4a9db63d35ba.mov

2021-11-21 05:50 UTC, YuyaYoshioka commented
実装に関係にない細かい指摘になるけど，今回はこのままで大丈夫
- サーバーサイドで1PR，フロントエンドで1PRって粒度がいいと思う
  - もしもAPIだけの開発，フロントだけの開発になった時は，お互いどういった設計がいいのかをきっちり決めてから実装することになると思うのだが，一人で作るときも，APIを実装してからフロントを実装するというクセをつけておくことで，フロント側が求めているデータ，バックエンドに送って欲しいデータ・処理を設計する力が身につくと考えている
  - そもそもコードレビューしやすい
- スクリーンショットは一番最初のDescriptionに貼っておいた方が見やすい

2021-11-21 05:56 UTC, YuyaYoshioka commented on server/spec/mutations/update_user_spec.rb
> +    let!(:user) { create(:user, name: 'user') }
この`user`変数他で使ってないのだから，beforeで良さそう

2021-11-21 05:56 UTC, YuyaYoshioka commented on server/spec/mutations/update_user_spec.rb
> +      it 'should user name changes' do
英語がおかしい

2021-11-21 05:56 UTC, YuyaYoshioka commented on server/spec/mutations/update_user_spec.rb
> +      let!(:other_user) { create(:user, name: 'update user') }
同じくbeforeで良さそう

2021-11-21 05:56 UTC, YuyaYoshioka commented on server/spec/mutations/update_user_spec.rb
> +      it 'should user name does not change' do
英語がおかしい

2021-11-21 05:57 UTC, YuyaYoshioka commented on server/spec/mutations/update_user_spec.rb
> +    context 'when update user name is nil' do
nilというよりは，invalidとかで良さそう

2021-11-21 05:57 UTC, YuyaYoshioka commented on server/spec/mutations/update_user_spec.rb
> +      it 'should user name does not change' do
英語がおかしい

2021-11-21 06:02 UTC, YuyaYoshioka commented on client/src/pages/userPage.tsx
> +      ) : (
isEditModeで，編集中の画面とユーザーページを出し分けるのではなくて，ユーザーの編集をModalで行えるようにしたらいいのでは？

2021-11-21 06:04 UTC, YuyaYoshioka requested changes
編集画面をModalにした方がいい気がする。
Modalの変更後に他のところは再レビューするわ

2021-11-21 12:39 UTC, atsuya02 commented on server/spec/mutations/update_user_spec.rb
> +    let!(:user) { create(:user, name: 'user') }
下の`user.reload.name`で使っているかも

2021-11-21 13:15 UTC, atsuya02 commented
@YuyaYoshioka 
モーダルは自作した方がいい？
それとも[ライブラリ](https://github.com/reactjs/react-modal)使った方がいい？

2021-11-21 13:32 UTC, YuyaYoshioka commented
自作でやってみよう 👍

2021-11-22 12:17 UTC, atsuya02 commented on client/src/pages/userPage.tsx
> +        {loginUser === paramsUserName && (
`loginUser === paramsUserName`を`getLoginUserName() === paramsUserName`で実装した方がいい？

2021-11-22 12:17 UTC, atsuya02 commented on client/src/pages/userPage.tsx
> +        {loginUser === paramsUserName && (
`loginUser === paramsUserName`を`getLoginUserName() === paramsUserName`で実装した方がいい？

2021-11-22 12:39 UTC, atsuya02 commented
@YuyaYoshioka 
修正終わったよ

2021-11-23 10:56 UTC, YuyaYoshioka commented
> 更新が成功した際には、モーダルを閉じるだけではなく、navigateでページ遷移を行った。ユーザ詳細ページのURLはユーザ名で管理しており、更新されたユーザ名のURLに遷移する必要があるからである

ここら辺は最初の設計ミスやったな。後々リファクタリングしよう 👍

2021-11-23 11:01 UTC, YuyaYoshioka commented on server/spec/mutations/update_user_spec.rb
> +    let!(:user) { create(:user, name: 'user') }
「かも」はいらんやろ笑

2021-11-23 11:06 UTC, YuyaYoshioka commented on client/src/components/Modal.tsx
> +  );
これだとユーザーの更新を行う専用のモーダルになってしまっているから，汎用性がなくなってしまっている。
`children`で他の要素を持てるようModalコンポーネントを作って，別にUpdateUserModalコンポーネントを作れば良いのでは？

2021-11-23 11:07 UTC, YuyaYoshioka requested changes
Modalコンポーネントを汎用性あるものに修正して欲しい

2021-11-23 12:46 UTC, atsuya02 commented
@YuyaYoshioka 
修正終わったよ

2021-11-23 14:21 UTC, YuyaYoshioka commented on client/src/components/Modal.tsx
> +  showModal: boolean;
childrenの型も欲しい

2021-11-23 14:22 UTC, YuyaYoshioka commented on client/src/components/UpdateUserModal.tsx
> +    <UpdateUser currentName={currentName} handleCloseModal={handleCloseModal} />
`UpdateUser`コンポーネントの中身をここにベタがきすればいいと思う

2021-11-23 14:35 UTC, YuyaYoshioka commented on client/src/components/UpdateUser.tsx
> +      <Toaster />
これって`UserPage`にあるからいらないのでは？

2021-11-23 14:38 UTC, YuyaYoshioka commented on client/src/pages/userPage.tsx
> +  };
propsとして関数を渡すときには，useCallbackで再定義されないようにしておいた方がいい

2021-11-23 14:38 UTC, YuyaYoshioka commented on client/src/pages/userPage.tsx
> +  };
同じく，useCallback

2021-11-23 14:39 UTC, YuyaYoshioka commented on client/src/pages/userPage.tsx
> +        {loginUser === paramsUserName && (
現状のままでいい気がする

2021-11-23 15:35 UTC, YuyaYoshioka commented on client/src/pages/userPage.tsx
> +
この処理に関しては，もう少しコード読んで検討してみる

2021-11-23 15:36 UTC, YuyaYoshioka commented on client/src/components/UpdateUser.tsx
> +        setLoginUserName(res.data?.updateUser.user.name as string);
ここで処理が成功しているのに`data`がundefinedになりうるのに違和感を感じている。
もう少し調べてみる予定やし，調べてみて欲しい。

2021-11-23 15:37 UTC, YuyaYoshioka reviewed
レビューした。
もう少し調べたいことあるから指摘したところの修正を進めておいて欲しい

2021-11-24 00:15 UTC, atsuya02 commented on client/src/pages/userPage.tsx
> +  };
`handleOpenModal`はpropsで渡してないと思う

2021-11-24 00:18 UTC, atsuya02 commented
@YuyaYoshioka 
修正終わったよ

2021-11-24 00:55 UTC, atsuya02 commented on client/src/components/UpdateUser.tsx
> +        setLoginUserName(res.data?.updateUser.user.name as string);
[MDN](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Promise/then#return_value)の記事参考になる？

2021-11-24 13:56 UTC, YuyaYoshioka commented on client/src/components/UpdateUser.tsx
> +        setLoginUserName(res.data?.updateUser.user.name as string);
どちらかというとApolloClientの問題な気がする 🤔

2021-11-24 16:46 UTC, atsuya02 commented on client/src/components/UpdateUser.tsx
> +        setLoginUserName(res.data?.updateUser.user.name as string);
[ApolloClient](https://www.apollographql.com/docs/react/data/mutations/#usemutation-api)に`ignoreResults`オプションが`true`の時に`data`が`undefined`になるとは書いてあった

<img width="557" alt="image" src="https://user-images.githubusercontent.com/73219274/143279659-d2f454d7-f2d1-4b49-971c-a99116b92b8f.png">

2021-11-25 14:04 UTC, YuyaYoshioka commented on client/src/components/UpdateUser.tsx
> +        setLoginUserName(res.data?.updateUser.user.name as string);
default では false みたいやから違いそうやな
https://www.apollographql.com/docs/react/data/mutations/#ignoreresults

2021-11-25 14:52 UTC, atsuya02 commented on client/src/components/UpdateUser.tsx
> +        setLoginUserName(res.data?.updateUser.user.name as string);
`useMutation`を最初に実行した時は`undefined`になるからかな
https://github.com/apollographql/react-apollo/issues/3234

2021-11-27 09:59 UTC, YuyaYoshioka commented on client/src/components/UpdateUserModal.tsx
> +        navigate(`/user/${res.data?.updateUser.user.name as string}`);
一時的にこれで回避するしかない気がした
```suggestion
        if (!res.data) {
          toast.error('Update failed!', {
            id: updateUserToastId,
          });

          return;
        }

        const {user} = res.data.updateUser;
        setLoginUserName(user.name);
        toast.success('Update completed', {
          id: updateUserToastId,
        });
        navigate(`/user/${user.name}`);
```

2021-11-27 10:00 UTC, YuyaYoshioka reviewed
レビューした

2021-11-27 10:02 UTC, YuyaYoshioka commented on client/src/pages/userPage.tsx
> +  const loginUser = getLoginUserName();
loginUserNameでは？

2021-11-27 14:58 UTC, atsuya02 commented
@YuyaYoshioka 
修正終わったよ

2021-11-27 15:42 UTC, YuyaYoshioka approved these changes
LGTM

2021-11-27 16:04 UTC, merged