ユーザ削除機能作成
atsuya02/promote-music-app pull request #40
Opened 2021-11-15 15:05 UTC by atsuya02

2021-11-15 15:08 UTC, atsuya02 commented
https://user-images.githubusercontent.com/73219274/141805163-05fedfa8-e5b7-42de-bef9-de8be4ed6884.mov

2021-11-15 15:15 UTC, atsuya02 commented
@YuyaYoshioka 
確認お願い。

2021-11-21 06:11 UTC, YuyaYoshioka commented on server/app/graphql/mutations/delete_user.rb
> +    # end
細かいけど，コメント消した方が良さそう
他のところはスルーしてしまっていた 🙈

2021-11-21 06:20 UTC, YuyaYoshioka commented on server/app/graphql/mutations/delete_user.rb
> +      end
これってUserが存在しないケースって考えられないのでは？
また，削除成功時にuserを返すってのは違和感を感じる。普通に何も返さなくて良さそう。
```suggestion
      user = User.find_by!(name: name)
      if !user.destroy
        raise GraphQL::ExecutionError, "Failed to delete user"
      end
```

2021-11-21 06:21 UTC, YuyaYoshioka commented on server/spec/mutations/delete_user_spec.rb
> +    end
このケースは考えなくて良さそう

2021-11-21 06:21 UTC, YuyaYoshioka commented on server/spec/mutations/delete_user_spec.rb
> +    end
このケースは考えなくて良さそう

2021-11-21 06:24 UTC, YuyaYoshioka commented on server/spec/mutations/delete_user_spec.rb
> +      it 'should user is deleted' do
英語がおかしい

2021-11-21 06:58 UTC, YuyaYoshioka commented on server/spec/mutations/delete_user_spec.rb
> +    let!(:user_artist_2) { create(:user_artist, user: user, artist: artist_2) }
```suggestion
    let!(:artist_1) { create(:artist) }
    let!(:artist_2) { create(:artist) }
    
    before do
      create(:user, name: 'user', artists: [artist1, artist2])
    end
```
で書けそう

2021-11-21 07:19 UTC, YuyaYoshioka commented on client/src/pages/userPage.tsx
> +    const toastDeleteUserId = toast.loading('Loading...');
toastのメッセージを識別するためのIDなのだから，`deleteUserToastId `の方が誤解がなくて良さそう

2021-11-21 07:29 UTC, YuyaYoshioka commented on client/src/pages/userPage.tsx
> +                (userRef: User) =>
`existingUserRefs: User[]`で型定義をしているのだから，ここが冗長になっている

2021-11-21 07:47 UTC, YuyaYoshioka commented on client/src/pages/userPage.tsx
> +                  res.data?.deleteUser.user.id !== readField('id', userRef),
サーバーから削除したuserの情報を返さなくても，
`paramsUserName`が存在するのだから，これを使用すれば良いのでは？
```suggestion
                  paramsUserName !== readField('name', userRef),
```

2021-11-21 07:48 UTC, YuyaYoshioka requested changes
レビューした

2021-11-21 13:09 UTC, atsuya02 commented
@YuyaYoshioka 
修正終わったよ

2021-11-21 13:46 UTC, YuyaYoshioka commented on server/app/graphql/mutations/delete_user.rb
> +    field :user, Types::UserType, null: false
これいらなさそう

2021-11-21 13:47 UTC, YuyaYoshioka commented on server/spec/mutations/delete_user_spec.rb
> +    subject { ServerSchema.execute(query_string, variables: { name: name }) }
行間あった方が見やすい
rubocopに怒られなかった？

2021-11-21 13:48 UTC, YuyaYoshioka commented on client/src/lib/user.ts
> +      }
これもいらなくなりそう

2021-11-21 13:48 UTC, YuyaYoshioka requested changes
レビューした

2021-11-21 15:30 UTC, atsuya02 commented on server/spec/mutations/delete_user_spec.rb
> +    subject { ServerSchema.execute(query_string, variables: { name: name }) }
今回はrubocop入れてないわ
今やってるPR終わったら導入する😅

2021-11-21 15:46 UTC, atsuya02 commented on client/src/lib/user.ts
> +      }
Playground のDOCS参照すると戻り値は違う値返す必要がありそう

<img width="279" alt="image" src="https://user-images.githubusercontent.com/73219274/142768862-e1b2c951-9abd-4699-b76a-52bcda899ad7.png">

2021-11-21 15:48 UTC, atsuya02 commented
@YuyaYoshioka 
修正終わったよ

2021-11-23 11:27 UTC, YuyaYoshioka commented on server/spec/mutations/delete_user_spec.rb
> +              name
ここミスってる

2021-11-23 11:28 UTC, YuyaYoshioka reviewed
レビューした

2021-11-23 12:58 UTC, atsuya02 commented
@YuyaYoshioka 
修正終わったよ

2021-11-23 14:20 UTC, YuyaYoshioka approved these changes
インデントだけよしなに修正しておいて
LGTM

2021-11-27 16:08 UTC, merged